#!/usr/bin/env python3
"""Generate INDEX.md, a catalog of every solution in the repository.

Walks the LeetCode, HackerRank, and Codility trees, extracts metadata from each
file's path and header comments, and writes a Markdown index. Re-run after
adding solutions to keep the catalog current:

    python3 scripts/generate_index.py
"""

import re
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent


def source_link(rel: Path) -> str:
    """A Markdown link to a repo file, URL-encoding spaces and parentheses
    so the path survives Markdown rendering."""
    return f"[source]({quote(rel.as_posix(), safe='/')})"


def header_lines(path: Path, count: int = 4) -> list[str]:
    """Return the first `count` non-empty lines of a file."""
    lines = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if stripped:
                lines.append(stripped)
            if len(lines) >= count:
                break
    return lines


def leetcode_rows() -> list[tuple]:
    rows = []
    for path in sorted((ROOT / "LeetCode" / "python").glob("*.py")):
        m = re.match(r"(\d+)\s+(.*)", path.stem)
        if not m:
            continue
        number, title = m.group(1), m.group(2)
        url = ""
        for line in header_lines(path, 2):
            um = re.search(r"https?://\S+", line)
            if um:
                url = um.group(0)
                break
        rows.append((number, title, url, path.relative_to(ROOT)))
    # SQL solutions live alongside the Python ones.
    for path in sorted((ROOT / "LeetCode" / "sql").glob("*.sql")):
        m = re.match(r"(\d+)\s+(.*)", path.stem)
        if not m:
            continue
        rows.append((m.group(1), m.group(2) + " (SQL)", "", path.relative_to(ROOT)))
    return sorted(rows, key=lambda r: int(r[0]))


def solution_dirs(base: Path) -> list[Path]:
    return sorted(p for p in base.rglob("Solution.py"))


def hackerrank_rows() -> list[tuple]:
    rows = []
    base = ROOT / "HackerRank"
    for path in solution_dirs(base):
        parts = path.relative_to(
            base
        ).parts  # <Track>/<Category?>/<Problem>/Solution.py
        track = parts[0]
        problem = parts[-2]
        category = " / ".join(parts[1:-2]) if len(parts) > 3 else ""
        url = ""
        for line in header_lines(path, 2):
            um = re.search(r"https?://\S+", line)
            if um:
                url = um.group(0)
                break
        rows.append((track, category, problem, url, path.relative_to(ROOT)))
    return rows


def codility_rows() -> list[tuple]:
    rows = []
    base = ROOT / "Codility"
    for path in solution_dirs(base):
        parts = path.relative_to(base).parts  # <NN. Lesson>/<Problem>/Solution.py
        lesson, problem = parts[0], parts[-2]
        url, difficulty = "", ""
        for line in header_lines(path, 3):
            um = re.search(r"https?://\S+", line)
            if um and not url:
                url = um.group(0)
            elif line.startswith("#"):
                tag = line.lstrip("# ").strip()
                if tag in {
                    "Painless",
                    "Respectable",
                    "Effortless",
                    "Ambitious",
                    "Crafty",
                }:
                    difficulty = tag
        rows.append((lesson, problem, difficulty, url, path.relative_to(ROOT)))
    return rows


def link(text: str, url: str) -> str:
    return f"[{text}]({url})" if url else text


def main() -> None:
    lc = leetcode_rows()
    hr = hackerrank_rows()
    cod = codility_rows()

    out = ["# Problem Index", ""]
    out.append(
        "Auto-generated by [`scripts/generate_index.py`](scripts/generate_index.py)."
    )
    out.append(
        f"Totals: {len(lc)} LeetCode · {len(hr)} HackerRank · {len(cod)} Codility."
    )
    out.append("")

    out.append(f"## LeetCode ({len(lc)})")
    out.append("")
    out.append("| # | Problem | Solution |")
    out.append("| --- | --- | --- |")
    for number, title, url, rel in lc:
        out.append(f"| {number} | {link(title, url)} | {source_link(rel)} |")
    out.append("")

    out.append(f"## HackerRank ({len(hr)})")
    out.append("")
    out.append("| Track | Category | Problem | Solution |")
    out.append("| --- | --- | --- | --- |")
    for track, category, problem, url, rel in hr:
        out.append(
            f"| {track} | {category} | {link(problem, url)} | {source_link(rel)} |"
        )
    out.append("")

    out.append(f"## Codility ({len(cod)})")
    out.append("")
    out.append("| Lesson | Problem | Difficulty | Solution |")
    out.append("| --- | --- | --- | --- |")
    for lesson, problem, difficulty, url, rel in cod:
        out.append(
            f"| {lesson} | {link(problem, url)} | {difficulty} | {source_link(rel)} |"
        )
    out.append("")

    (ROOT / "INDEX.md").write_text("\n".join(out), encoding="utf-8")
    print(
        f"Wrote INDEX.md: {len(lc)} LeetCode, {len(hr)} HackerRank, {len(cod)} Codility."
    )


if __name__ == "__main__":
    main()
